name: kolshy_vendor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  gif: ^2.2.0
  file_picker: ^8.0.0
  flutter_dropzone: ^4.2.1
  dotted_border: ^3.1.0
  flutter_markdown: ^0.7.7+1
  flutter_quill: ^11.4.2
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  image_picker: ^1.2.0
  shared_preferences: ^2.2.2
  intl_phone_field: ^3.2.0
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.2
  sign_in_with_apple: ^7.0.1
  flutter_web_auth_2: ^4.0.0
  flutter_html: ^3.0.0-alpha.6
  provider: ^6.0.5
  syncfusion_flutter_charts: ^31.1.20
  syncfusion_flutter_datepicker: ^31.1.20
  path_provider: ^2.1.5
  dio: ^5.4.3
  flutter_secure_storage: ^9.0.0+1
  connectivity_plus: ^6.1.5
  graphql_flutter: ^5.1.2
  uuid: ^4.4.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  fl_chart: ^0.68.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/