name: vendor_app
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  gif: ^2.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  assets:
    # Logo
    - assets/kolshy_logo_noir.gif

    # Avatar placeholder
    - assets/avatar_placeholder.jpg

    # All your icon PNGs (active/inactive states)
    - assets/icons/dashboard_on.png
    - assets/icons/dashboard_off.png
    - assets/icons/orders_on.png
    - assets/icons/orders_off.png
    - assets/icons/product_on.png
    - assets/icons/product_off.png
    - assets/icons/analytics_on.png
    - assets/icons/analytics_off.png
    - assets/icons/transactions_on.png
    - assets/icons/transactions_off.png
    - assets/icons/revenue_on.png
    - assets/icons/revenue_off.png
    - assets/icons/review_on.png
    - assets/icons/review_off.png

    # Bottom navigation icons
    - assets/icons/menu.png
    - assets/icons/home.png
    - assets/icons/chat.png
    - assets/icons/bell.png